settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: break-reminder
  path: /Users/gabriel/goworkspace/src/github.com/Gabriel-diez/break-reminder
  commands:
    fmt:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
